language: node_js
notifications:
  email: false
node_js:
  - node
  - lts/*
  - 8
after_success:
  - test `node --version | cut -c 2,3` -eq 10 && npm run coverage
  - npx semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
