sudo: false
language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - "12"
  - "10"
  - "8"
after_success:
  - test `node --version | cut -c 2,3` -eq 10 && npm run coverage
  - npx semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
